### ISSUE TITLE
[TOAD] - try again button

### ISSUE THREAD

**Issue by Zulbukharov** [01-edu/public#91]
**Describe the bug**
after the first attempt to pass tests, the repeat button does not respond. Before, admin declined me. tried with Safari and Mozilla 

**To Reproduce**
1. pass the test
2. be declined by admin
3. try again

**Screenshots**
![](https://i.imgur.com/dqpdlfP.png)

**Additional context**

**Type**
Add the correct label to your bug report : blocking

**Priority**
Add the correct label to your bug report : normal

**Subject**
Add the correct labels to your bug report :  toad

**Comment by lfoussat** [comment]
I saw it today, I fixed it it's in a PR :)

**Comment by sakenism** [comment]
Dear Louise, it is not fixed. Today I trie games, got rejected and the button did not respond at all. I had to reload page to try again. Possible solution is to reload page when the button is pressed.
